baseURL = "https://fnichol.com/"
languageCode = "en-us"
title = "Fletcher Nichol"
googleAnalytics = "UA-147748480-1"

theme = "pickles"

[params]
# This will be the canonical "production" base URL for the site. If a `baseURL`
# is not equal to this value, then it will not be considered a production
# build/deployment.
ProdURL = "https://fnichol.com/"
