# Documentation: https://www.netlify.com/docs/netlify-toml-reference/

[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.62.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture --baseURL $DEPLOY_PRIME_URL"
